version: '3.4'

services:
    xpop-mainnet:
        container_name: xpop-mainnet
        image: xpop:service
        build: .
        volumes:
            - ./store:/usr/src/app/store
        environment:
          - EVENT_SOCKET_PORT=3000
          - PUBLIC_PORT=${PORT:-3000}
          - URL_PREFIX=${URL_PREFIX:-http://localhost:${PORT:-3000}}
          - NETWORKID=0
          - UNLURL=https://unl.xrplf.org
          - UNLKEY=ED42AEC58B701EEBB77356FFFEC26F83C1F0407263530F068C7C73D392C7E06FD1
          - NODES=wss://xrplcluster.com,wss://s2.ripple.com
          - FIELDSREQUIRED=Fee,Account,OperationLimit
          - NOVALIDATIONLOG=1
          - NOELIGIBLEFULLTXLOG=1
          - ONLYUNLVALIDATIONS=${ONLYUNLVALIDATIONS}
          - DEBUG=${DEBUG}
          - TELEMETRY=${TELEMETRY:-NO}
        restart: unless-stopped
        healthcheck:
            test: wget --spider -q http://localhost:3000/health || exit 1
            interval: 15s
            retries: 2
            start_period: 5s
            timeout: 5s
